export declare enum UserRole {
    ADMIN = "ADMIN",
    USER = "USER"
}
export declare enum TaskStatus {
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    PAUSED = "PAUSED",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    CANCELLED = "CANCELLED"
}
export declare enum TaskStage {
    SCRIPT_UPLOADED = "SCRIPT_UPLOADED",
    STORYBOARD_GENERATED = "STORYBOARD_GENERATED",
    CHARACTER_DESIGNED = "CHARACTER_DESIGNED",
    SCENE_GENERATED = "SCENE_GENERATED",
    KEYFRAME_GENERATING = "KEYFRAME_GENERATING",
    KEYFRAME_COMPLETED = "KEYFRAME_COMPLETED",
    VIDEO_GENERATING = "VIDEO_GENERATING",
    VIDEO_COMPLETED = "VIDEO_COMPLETED",
    FINAL_COMPOSING = "FINAL_COMPOSING",
    COMPLETED = "COMPLETED"
}
export declare enum AssetType {
    WORKFLOW_TEST = "workflow_test",
    TASK_EXECUTION = "task_execution"
}
