/**
 * 共享枚举定义
 * @module shared/constants/enums
 */

/**
 * 用户角色枚举
 */
export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

/**
 * 任务状态枚举
 */
export enum TaskStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

/**
 * 任务阶段枚举
 */
export enum TaskStage {
  SCRIPT_UPLOADED = 'SCRIPT_UPLOADED',
  STORYBOARD_GENERATED = 'STORYBOARD_GENERATED',
  CHARACTER_DESIGNED = 'CHARACTER_DESIGNED',
  SCENE_GENERATED = 'SCENE_GENERATED',
  KEYFRAME_GENERATING = 'KEYFRAME_GENERATING',
  KEYFRAME_COMPLETED = 'KEYFRAME_COMPLETED',
  VIDEO_GENERATING = 'VIDEO_GENERATING',
  VIDEO_COMPLETED = 'VIDEO_COMPLETED',
  FINAL_COMPOSING = 'FINAL_COMPOSING',
  COMPLETED = 'COMPLETED',
}

/**
 * 资产类型枚举
 */
export enum AssetType {
  WORKFLOW_TEST = 'workflow_test',
  TASK_EXECUTION = 'task_execution',
}

/**
 * 资产状态枚举
 */
export enum AssetStatus {
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  TRASHED = 'TRASHED',
  REPLACED = 'REPLACED',
}

/**
 * 工作流节点类型枚举
 */
export enum WorkflowNodeType {
  START = 'START',
  END = 'END',
  LLM_TOOL = 'LLM_TOOL',
  LLM_PARSE_SCRIPT = 'LLM_PARSE_SCRIPT',
  GENERATE_STORYBOARD = 'GENERATE_STORYBOARD',
  GENERATE_CHARACTER_IMAGES = 'GENERATE_CHARACTER_IMAGES',
  HUMAN_REVIEW_ASSETS = 'HUMAN_REVIEW_ASSETS',
  HUMAN_BREAKPOINT = 'HUMAN_BREAKPOINT',
  GENERATE_SCENE_IMAGE = 'GENERATE_SCENE_IMAGE',
  GENERATE_KEYFRAMES = 'GENERATE_KEYFRAMES',
  GENERATE_VIDEO = 'GENERATE_VIDEO',
  FINAL_COMPOSE = 'FINAL_COMPOSE',
}

/**
 * 工作流运行状态
 */
export enum WorkflowRunStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  WAITING_HUMAN = 'WAITING_HUMAN',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

/**
 * 节点运行状态
 */
export enum NodeRunStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  WAITING_HUMAN = 'WAITING_HUMAN',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

/**
 * 人工审核决策
 */
export enum HumanReviewDecision {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  REPLACE = 'REPLACE',
}

/**
 * Provider 类型
 */
export enum ProviderType {
  LLM = 'LLM',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
}
